/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RehabRouteImport } from './routes/rehab'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BodyRouteImport } from './routes/body'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StretchIdRouteImport } from './routes/stretch.$id'
import { Route as IssueIdRouteImport } from './routes/issue.$id'

const RehabRoute = RehabRouteImport.update({
  id: '/rehab',
  path: '/rehab',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StretchIdRoute = StretchIdRouteImport.update({
  id: '/stretch/$id',
  path: '/stretch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIdRoute = IssueIdRouteImport.update({
  id: '/issue/$id',
  path: '/issue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/profile': typeof ProfileRoute
  '/rehab': typeof RehabRoute
  '/issue/$id': typeof IssueIdRoute
  '/stretch/$id': typeof StretchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/profile': typeof ProfileRoute
  '/rehab': typeof RehabRoute
  '/issue/$id': typeof IssueIdRoute
  '/stretch/$id': typeof StretchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/profile': typeof ProfileRoute
  '/rehab': typeof RehabRoute
  '/issue/$id': typeof IssueIdRoute
  '/stretch/$id': typeof StretchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body'
    | '/profile'
    | '/rehab'
    | '/issue/$id'
    | '/stretch/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/body' | '/profile' | '/rehab' | '/issue/$id' | '/stretch/$id'
  id:
    | '__root__'
    | '/'
    | '/body'
    | '/profile'
    | '/rehab'
    | '/issue/$id'
    | '/stretch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyRoute: typeof BodyRoute
  ProfileRoute: typeof ProfileRoute
  RehabRoute: typeof RehabRoute
  IssueIdRoute: typeof IssueIdRoute
  StretchIdRoute: typeof StretchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rehab': {
      id: '/rehab'
      path: '/rehab'
      fullPath: '/rehab'
      preLoaderRoute: typeof RehabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stretch/$id': {
      id: '/stretch/$id'
      path: '/stretch/$id'
      fullPath: '/stretch/$id'
      preLoaderRoute: typeof StretchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$id': {
      id: '/issue/$id'
      path: '/issue/$id'
      fullPath: '/issue/$id'
      preLoaderRoute: typeof IssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyRoute: BodyRoute,
  ProfileRoute: ProfileRoute,
  RehabRoute: RehabRoute,
  IssueIdRoute: IssueIdRoute,
  StretchIdRoute: StretchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
